{
    "name": "HR Custom",
    "summary": "Customization on HR Attendance App",
    "category": "Human Resources",
    'author': 'pankaj',
    'maintainer': 'Kerlos',
    "license": "LGPL-3",
    'website': '',
    'version': '19.0.1.0.0',
    "depends": ["base", "hr_attendance", "hr_payroll", "hr", "hr_holidays"],
    "external_dependencies": {
        "python": ["toolz"],
    },
    "data": [
        "security/ir.model.access.csv",
        "security/hr_custom_security_groups.xml",
        "views/hr_attendance_view.xml",
        "views/hr_employee_view.xml",
        "views/hr_version_view.xml",
        "views/res_company_view.xml",
        'data/expiry_email_cron_view.xml',
        'data/hr_payroll_data.xml',
        'views/hr_leave.xml',
        'views/hr_leave_line.xml',
        'views/hr_leave_type.xml',
        'views/hr_leave_employee_policy.xml',
        'views/report_payslip_templates.xml',
        'views/resource_views.xml',
    ],
}