# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import api, fields, models, _


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    has_mrp_production_consolidated = fields.Boolean(
        "Is MO generated", compute='_compute_has_mrp_production_consolidated',
        store=True, groups='mrp.group_mrp_user', copy=False)

    consolidated_mrp_ids = fields.Many2many('mrp.production.consolidated', copy=False)

    @api.depends('consolidated_mrp_ids')
    def _compute_has_mrp_production_consolidated(self):
        for rec in self:
            rec.has_mrp_production_consolidated = len(rec.consolidated_mrp_ids) > 0

    def action_view_mrp_production_consolidated(self):
        self.ensure_one()
        action = {
            'res_model': 'mrp.production.consolidated',
            'type': 'ir.actions.act_window',
        }
        if len(self.consolidated_mrp_ids) == 1:
            action.update({
                'view_mode': 'form',
                'res_id': self.consolidated_mrp_ids.id,
            })
        else:
            action.update({
                'name': _("Manufacturing Orders Generated by %s", self.name),
                'domain': [('id', 'in', self.consolidated_mrp_ids.ids)],
                'view_mode': 'tree,form',
            })
        return action
