from . import hr_attandance
from . import hr_employee
from . import hr_contract
from . import hr_payroll
from . import res_company
from . import hr_leave
from . import hr_leave_line
from . import hr_leave_line_part
from . import hr_leave_type
from . import hr_leave_employee_policy
from . import resource_calendar_leaves